export interface Recipe {
  id: string;
  name: string;
  emoji: string;
  prepMin: number;
  cookMin: number;
  tags: string[];
  ingredients: string[];
  steps: string[];
}

export const RECIPES: Recipe[] = [
  {
    id: 'overnight-oats',
    name: 'Overnight Oats',
    emoji: '🥣',
    prepMin: 5,
    cookMin: 0,
    tags: ['breakfast', 'meal-prep', 'vegetarian'],
    ingredients: [
      '80 g rolled oats',
      '240 ml milk (or plant milk)',
      '120 g Greek yogurt',
      '1 tbsp chia seeds',
      '1 tbsp honey or maple syrup',
      'Toppings: berries, banana, granola',
    ],
    steps: [
      'Combine oats, milk, yogurt, chia seeds, and sweetener in a jar or container.',
      'Stir well, seal the lid, and refrigerate overnight (at least 6 hours).',
      'In the morning, stir again — add a splash of milk if too thick.',
      'Top with your chosen fruits and granola, then serve cold.',
    ],
  },
  {
    id: 'avocado-toast',
    name: 'Avocado Toast',
    emoji: '🥑',
    prepMin: 5,
    cookMin: 3,
    tags: ['breakfast', 'vegetarian', 'quick'],
    ingredients: [
      '2 slices sourdough or wholegrain bread',
      '1 ripe avocado',
      'Juice of ½ lemon',
      'Pinch of chilli flakes',
      'Salt and black pepper to taste',
      'Optional: 2 poached eggs, cherry tomatoes',
    ],
    steps: [
      'Toast the bread until golden and crisp.',
      'Halve the avocado, remove the stone, and scoop the flesh into a bowl.',
      'Mash the avocado with lemon juice, salt, and pepper to your preferred texture.',
      'Spread generously on toast, sprinkle with chilli flakes.',
      'Top with poached eggs or cherry tomatoes if desired. Serve immediately.',
    ],
  },
  {
    id: 'chicken-stir-fry',
    name: 'Chicken Stir-Fry',
    emoji: '🍜',
    prepMin: 15,
    cookMin: 12,
    tags: ['dinner', 'high-protein', 'meal-prep'],
    ingredients: [
      '400 g chicken breast, thinly sliced',
      '2 tbsp soy sauce',
      '1 tbsp oyster sauce',
      '1 tsp sesame oil',
      '1 tbsp cornstarch',
      '2 cloves garlic, minced',
      '1 tsp fresh ginger, grated',
      '1 red bell pepper, sliced',
      '200 g broccoli florets',
      '1 medium carrot, julienned',
      '2 tbsp vegetable oil',
      '2 spring onions, sliced',
      'Cooked rice or noodles, to serve',
    ],
    steps: [
      'Toss sliced chicken with soy sauce, oyster sauce, sesame oil, and cornstarch. Set aside for 10 minutes.',
      'Heat 1 tbsp oil in a wok or large frying pan over high heat.',
      'Stir-fry the chicken in a single layer for 3–4 minutes until cooked through. Remove and set aside.',
      'Add remaining oil. Stir-fry garlic and ginger for 30 seconds.',
      'Add broccoli, carrot, and pepper. Stir-fry for 3–4 minutes until tender-crisp.',
      'Return the chicken to the pan, toss everything together, and cook for 1 minute.',
      'Garnish with spring onions and serve over rice or noodles.',
    ],
  },
  {
    id: 'greek-salad',
    name: 'Greek Salad',
    emoji: '🥗',
    prepMin: 10,
    cookMin: 0,
    tags: ['lunch', 'vegetarian', 'quick'],
    ingredients: [
      '2 large tomatoes, cut into wedges',
      '1 cucumber, halved and sliced',
      '½ red onion, thinly sliced',
      '100 g Kalamata olives',
      '200 g feta cheese, cubed',
      '3 tbsp extra-virgin olive oil',
      '1 tbsp red wine vinegar',
      '1 tsp dried oregano',
      'Salt and black pepper to taste',
    ],
    steps: [
      'Combine tomatoes, cucumber, red onion, and olives in a large bowl.',
      'Whisk together olive oil, red wine vinegar, oregano, salt, and pepper.',
      'Pour the dressing over the vegetables and toss gently.',
      'Top with feta cubes (do not crumble — keep them chunky).',
      'Serve immediately or refrigerate for up to 1 hour for a marinated flavour.',
    ],
  },
  {
    id: 'lentil-soup',
    name: 'Red Lentil Soup',
    emoji: '🍲',
    prepMin: 10,
    cookMin: 30,
    tags: ['lunch', 'dinner', 'vegan', 'meal-prep'],
    ingredients: [
      '300 g red lentils, rinsed',
      '1 large onion, diced',
      '3 cloves garlic, minced',
      '2 medium carrots, diced',
      '1 can (400 g) diced tomatoes',
      '1.2 L vegetable stock',
      '2 tsp ground cumin',
      '1 tsp smoked paprika',
      '½ tsp turmeric',
      '2 tbsp olive oil',
      'Juice of 1 lemon',
      'Salt and pepper to taste',
      'Fresh parsley or coriander, to garnish',
    ],
    steps: [
      'Heat olive oil in a large pot over medium heat. Sauté onion for 5 minutes until soft.',
      'Add garlic, carrots, cumin, paprika, and turmeric. Cook for 2 minutes, stirring.',
      'Add lentils, diced tomatoes, and vegetable stock. Bring to a boil.',
      'Reduce heat, cover, and simmer for 20–25 minutes until lentils are tender.',
      'Use a stick blender to partially blend for a creamy-chunky texture (or blend fully for smooth).',
      'Season with lemon juice, salt, and pepper. Serve topped with fresh herbs.',
    ],
  },
  {
    id: 'banana-pancakes',
    name: 'Banana Pancakes',
    emoji: '🥞',
    prepMin: 5,
    cookMin: 10,
    tags: ['breakfast', 'vegetarian', 'quick'],
    ingredients: [
      '2 ripe bananas',
      '2 eggs',
      '60 g rolled oats (or 50 g plain flour)',
      '1 tsp baking powder',
      '½ tsp cinnamon',
      'Pinch of salt',
      'Butter or coconut oil, for frying',
      'Maple syrup and fresh fruit, to serve',
    ],
    steps: [
      'Mash bananas in a bowl until smooth.',
      'Add eggs, oats (or flour), baking powder, cinnamon, and salt. Mix well.',
      'Heat a non-stick pan over medium heat and add a small amount of butter.',
      'Pour 2–3 tbsp of batter per pancake. Cook for 2–3 minutes until bubbles form.',
      'Flip carefully and cook for 1–2 minutes more until golden.',
      'Serve with maple syrup and sliced fresh fruit.',
    ],
  },
  {
    id: 'salmon-bowl',
    name: 'Teriyaki Salmon Bowl',
    emoji: '🐟',
    prepMin: 10,
    cookMin: 15,
    tags: ['dinner', 'high-protein', 'meal-prep'],
    ingredients: [
      '2 salmon fillets (approx. 150 g each)',
      '3 tbsp soy sauce',
      '2 tbsp honey',
      '1 tbsp rice vinegar',
      '1 tsp sesame oil',
      '1 clove garlic, minced',
      '150 g brown rice, cooked',
      '1 avocado, sliced',
      '100 g edamame, shelled',
      '½ cucumber, ribboned',
      '1 tbsp sesame seeds',
      '2 spring onions, sliced',
    ],
    steps: [
      'Mix soy sauce, honey, rice vinegar, sesame oil, and garlic in a small bowl.',
      'Marinate salmon fillets in half the sauce for at least 5 minutes.',
      'Heat a non-stick pan over medium-high heat. Cook salmon skin-side up for 3–4 minutes.',
      'Flip and cook for another 3 minutes, adding the remaining sauce in the last minute.',
      'Assemble bowls: rice base, then salmon, avocado, edamame, and cucumber.',
      'Drizzle any remaining pan sauce over the bowl. Garnish with sesame seeds and spring onions.',
    ],
  },
  {
    id: 'veggie-chilli',
    name: 'Veggie Chilli',
    emoji: '🌶️',
    prepMin: 15,
    cookMin: 35,
    tags: ['dinner', 'vegan', 'meal-prep'],
    ingredients: [
      '1 can (400 g) black beans, drained',
      '1 can (400 g) kidney beans, drained',
      '1 can (400 g) diced tomatoes',
      '1 large onion, diced',
      '3 cloves garlic, minced',
      '1 red and 1 green bell pepper, diced',
      '1 courgette, diced',
      '2 tsp chilli powder',
      '1 tsp ground cumin',
      '1 tsp smoked paprika',
      '200 ml vegetable stock',
      '2 tbsp olive oil',
      'Salt and pepper to taste',
      'Soured cream, cheddar, or avocado to serve',
    ],
    steps: [
      'Heat olive oil in a large pot. Sauté onion and peppers for 5 minutes.',
      'Add garlic, courgette, chilli powder, cumin, and paprika. Cook for 2 minutes.',
      'Add both cans of beans, diced tomatoes, and vegetable stock.',
      'Bring to a boil, then reduce heat. Simmer uncovered for 25–30 minutes, stirring occasionally.',
      'Season with salt and pepper. Serve with rice and your chosen toppings.',
    ],
  },
  {
    id: 'egg-fried-rice',
    name: 'Egg Fried Rice',
    emoji: '🍳',
    prepMin: 5,
    cookMin: 10,
    tags: ['lunch', 'dinner', 'quick', 'meal-prep'],
    ingredients: [
      '300 g cooked cold rice (day-old works best)',
      '3 eggs, beaten',
      '100 g frozen peas',
      '3 spring onions, sliced',
      '3 tbsp soy sauce',
      '1 tsp sesame oil',
      '2 tbsp vegetable oil',
      '2 cloves garlic, minced',
      '1 tsp fresh ginger (optional)',
    ],
    steps: [
      'Heat 1 tbsp oil in a wok or large pan over high heat.',
      'Add garlic (and ginger if using) — stir-fry for 30 seconds.',
      'Push to one side, add remaining oil and pour in eggs. Scramble lightly.',
      'Before eggs fully set, add cold rice and frozen peas. Toss everything together.',
      'Stir-fry for 3–4 minutes, breaking up any rice clumps.',
      'Add soy sauce and sesame oil. Toss to coat evenly.',
      'Garnish with spring onions and serve immediately.',
    ],
  },
  {
    id: 'smoothie-bowl',
    name: 'Smoothie Bowl',
    emoji: '🫐',
    prepMin: 8,
    cookMin: 0,
    tags: ['breakfast', 'vegan', 'quick'],
    ingredients: [
      '2 frozen bananas',
      '150 g frozen mixed berries',
      '60 ml plant milk (just enough to blend)',
      'Toppings: granola, fresh berries, sliced kiwi, coconut flakes, chia seeds',
    ],
    steps: [
      'Add frozen bananas and berries to a blender with the minimal amount of plant milk.',
      'Blend until thick and creamy — it should be much thicker than a drinkable smoothie.',
      'Pour into a bowl and smooth the top with a spoon.',
      'Arrange toppings in rows or sections for a colourful presentation.',
      'Serve immediately before the base melts.',
    ],
  },
  {
    id: 'turkey-wraps',
    name: 'Turkey & Hummus Wraps',
    emoji: '🌯',
    prepMin: 10,
    cookMin: 0,
    tags: ['lunch', 'high-protein', 'quick', 'meal-prep'],
    ingredients: [
      '2 large wholegrain tortillas',
      '150 g sliced turkey breast',
      '4 tbsp hummus',
      'Handful of baby spinach',
      '½ cucumber, sliced into strips',
      '1 large tomato, sliced',
      '¼ red onion, thinly sliced',
      'Salt, pepper, and a squeeze of lemon',
    ],
    steps: [
      'Lay the tortillas flat and spread 2 tbsp hummus over each one.',
      'Layer turkey slices, spinach, cucumber, tomato, and red onion.',
      'Season with salt, pepper, and a squeeze of lemon juice.',
      'Fold in the sides of the tortilla, then roll tightly from the bottom up.',
      'Slice in half diagonally and serve, or wrap in foil for packed lunch.',
    ],
  },
  {
    id: 'pasta-primavera',
    name: 'Pasta Primavera',
    emoji: '🍝',
    prepMin: 10,
    cookMin: 20,
    tags: ['dinner', 'vegetarian'],
    ingredients: [
      '320 g pasta (penne or fusilli)',
      '2 tbsp olive oil',
      '3 cloves garlic, minced',
      '1 courgette, sliced',
      '1 yellow bell pepper, diced',
      '100 g cherry tomatoes, halved',
      '80 g frozen peas',
      '100 ml single cream or crème fraîche',
      '40 g Parmesan, grated',
      'Salt, pepper, and fresh basil to taste',
    ],
    steps: [
      'Cook pasta in salted boiling water according to package instructions. Reserve 100 ml pasta water before draining.',
      'Heat olive oil in a large pan. Sauté garlic for 30 seconds.',
      'Add courgette and pepper — cook for 4–5 minutes until softened.',
      'Add cherry tomatoes and peas, cook for 2 minutes more.',
      'Stir in cream and half the Parmesan. Season with salt and pepper.',
      'Add drained pasta and toss, adding pasta water a little at a time to loosen the sauce.',
      'Serve topped with remaining Parmesan and fresh basil.',
    ],
  },
];
